# OSINT(TOC)
# export OSINT="$OSINTDIR/osint.sh"

## TABLE OF CONTENTS
## Files without TITLE_ASCII. e.g.(osint.sh -> CHILD PAGE[EXIT] -> toc.sh)
export TOC="$OSINTDIR/bin/toc.sh"

### CHILD PAGE
export MAPS_GEOLOCATION_AND_TRANSPORT="$OSINTDIR/bin/maps-geolocation-and-transport.sh"
export SOCIAL_MEDIA="$OSINTDIR/bin/social-media.sh"
export DOMAIN_IP_LINKS="$OSINTDIR/bin/domain-ip-links.sh"
export IMAGE_SEARCH_AND_IDENTIFICATION="$OSINTDIR/bin/image-search-and-identification.sh"
export CRYPTOCURRENCIES="$OSINTDIR/bin/cryptocurrencies.sh"
export MESSENGERS="$OSINTDIR/bin/messengers.sh"
export CODE="$OSINTDIR/bin/code.sh"
export SEARCH_ENGINES="$OSINTDIR/bin/search-engines.sh"
export TOOLS_FOR_GOOGLE="$OSINTDIR/bin/tools-for-google.sh"
export IOT="$OSINTDIR/bin/iot.sh"
export ARCHIVES="$OSINTDIR/bin/archives.sh"
export ARCHIVES_OF_DOCUMENTS="$OSINTDIR/bin/archives-of-documents.sh"
export DATASETS="$OSINTDIR/bin/datasets.sh"
export PASSWORDS_EMAILS_PHONE_NUMBERS="$OSINTDIR/bin/passwords-emails-phone-numbers.sh"
export PEOPLE_SEARCH="$OSINTDIR/bin/people-search.sh"
export SOCK_PUPPETS="$OSINTDIR/bin/sock-puppets.sh"
export NOOSINT_TOOLS="$OSINTDIR/bin/noosint-tools.sh"
export TOOLS_COLLECTIONS="$OSINTDIR/bin/tools-collections.sh"
export FILES="$OSINTDIR/bin/files.sh"
export IMEI_AND_SERIAL_NUMBERS="$OSINTDIR/bin/imei-and_-serial-numbers.sh"
export KEYWORDS_TRENDS_NEWS_ANALYTICS="$OSINTDIR/bin/keywords-trends-news-analytics.sh"
export APPS_AND_PROGRAMS="$OSINTDIR/bin/apps-and-programs.sh"
export BRANDS_COMPANIES_ITEMS="$OSINTDIR/bin/brands-companies-items.sh"
export MOVIES="$OSINTDIR/bin/movies.sh"
export TV_RADIO="$OSINTDIR/bin/tv-radio.sh"
export VIRTUALMACHINES_LINUX_DISTRIBUTIONS="$OSINTDIR/bin/virtualmachines-linux-distributions.sh"
export MY_PROJECTS="$OSINTDIR/bin/my-projects.sh"

#### OSINT/MAPS_GEOLOCATION_AND_TRANSPORT
export SOCIAL_MEDIA_AND_PHOTOS_MAPS="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/social-media-and-photos-maps.sh"
export NATURE_AVIATION="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/nature-aviation.sh"
export MARITIME="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/maritime.sh"
export RAILWAY="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/railway.sh"
export ROUTES="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/routes.sh"
export POLITICS_CONFLICTS_AND_CRISIS="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/politics-conflicts-and-crisis.sh"
export URBAN_AND_INDUSTRIAL_INFRASTRUCTURE="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/urban-and-industrial-infrastructure.sh"
export TRANSPORT="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/transport.sh"
export COMMUNICATIONS_INTERNET_TECHNOLOGIES="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/communications-Internet-technologies.sh"
export TOOLS="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/tools.sh"
export STREET_VIEW="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/street-view.sh"
export OTHER="$OSINTDIR/bin/MAPS_GEOLOCATION_AND_TRANSPORT/other.sh"

# OSINT/SOCIAL_MEDIA
export TWITTER="$OSINTDIR/bin/SOCIAL_MEDIA/twitter.sh"
export YOUTUBE="$OSINTDIR/bin/SOCIAL_MEDIA/youtube.sh"
export TIKTOK="$OSINTDIR/bin/SOCIAL_MEDIA/tiktok.sh"
export FACEBOOK="$OSINTDIR/bin/SOCIAL_MEDIA/facebook.sh"
export CLUBHOUSE="$OSINTDIR/bin/SOCIAL_MEDIA/clubhouse.sh"
export LINKEDIN="$OSINTDIR/bin/SOCIAL_MEDIA/linkedin.sh"
export XING="$OSINTDIR/bin/SOCIAL_MEDIA/xing.sh"
export REDDIT="$OSINTDIR/bin/SOCIAL_MEDIA/reddit.sh"
export ONLYFANS="$OSINTDIR/bin/SOCIAL_MEDIA/onlyfans.sh"
export TWITCH="$OSINTDIR/bin/SOCIAL_MEDIA/twitch.sh"
export FIDONET="$OSINTDIR/bin/SOCIAL_MEDIA/fidonet.sh"
export USENET="$OSINTDIR/bin/SOCIAL_MEDIA/usenet.sh"
export TUMBLR="$OSINTDIR/bin/SOCIAL_MEDIA/tumblr.sh"
export FLICKR="$OSINTDIR/bin/SOCIAL_MEDIA/flickr.sh"
export SPOTIFY="$OSINTDIR/bin/SOCIAL_MEDIA/spotify.sh"
export DISCORD="$OSINTDIR/bin/SOCIAL_MEDIA/discord.sh"
export YANDEX="$OSINTDIR/bin/SOCIAL_MEDIA/yandex.sh"
export INSTAGRAM="$OSINTDIR/bin/SOCIAL_MEDIA/instagram.sh"
export GOOGLE="$OSINTDIR/bin/SOCIAL_MEDIA/google.sh"
export PATREON="$OSINTDIR/bin/SOCIAL_MEDIA/patreon.sh"
export GITHUB="$OSINTDIR/bin/SOCIAL_MEDIA/github.sh"
export PARLER="$OSINTDIR/bin/SOCIAL_MEDIA/parler.sh"
export PORNHUB="$OSINTDIR/bin/SOCIAL_MEDIA/pornhub.sh"
export STEAM="$OSINTDIR/bin/SOCIAL_MEDIA/steam.sh"
export XBOX="$OSINTDIR/bin/SOCIAL_MEDIA/xbox.sh"
export VK="$OSINTDIR/bin/SOCIAL_MEDIA/vk.sh"
export OFFICE365="$OSINTDIR/bin/SOCIAL_MEDIA/office365.sh"
export ONEDRIVE="$OSINTDIR/bin/SOCIAL_MEDIA/onedrive.sh"
export UNIVERSAL="$OSINTDIR/bin/SOCIAL_MEDIA/universal.sh"
