// メニューの項目を定義するためのモジュールです。

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub enum MenuItem {
    MapsGeolocationTransport(Vec<MenuItem>),
    SocialMedia(Vec<MenuItem>),
    Downloaders(Vec<MenuItem>),
    DomainIPLinks,
    ImageSearchIdentification,
    Cryptocurrencies,
    Messengers,
    Code,
    SearchEngines,
    ToolsForDuckDuckGo,
    ToolsForGoogle,
    IOT,
    Archives,
    ArchivesOfDocuments,
    Datasets,
    PasswordsEmailsPhoneNumbers,
    PeopleSearch,
    SockPuppets,
    NOOSINTTools,
    ToolsCollections,
    Files,
    IMEISerialNumbers,
    NFT,
    KeywordsTrendsNewsAnalytics,
    AppsAndPrograms,
    BrandsCompaniesItems,
    Movies,
    TVRadio,
    VirtualMachinesLinux,
    MyProjects,
    Exit,
    SocialMediaPhotos,
    NatureAviation,
    Maritime,
    Railway,
    Routes,
    PoliticsConflicts,
    UrbanInfrastructure,
    Transport,
    Communications,
    Tools,
    StreetView,
    Other,
}

impl MenuItem {
    pub fn all() -> Vec<MenuItem> {
        use MenuItem::*;
        vec![
            MapsGeolocationTransport(vec![
                SocialMediaPhotos,
                NatureAviation,
                Maritime,
                Railway,
                Routes,
                PoliticsConflicts,
                UrbanInfrastructure,
                Transport,
                Communications,
                Tools,
                StreetView,
                Other,
            ]),
            SocialMedia(vec![]),
            Downloaders(vec![]),
            DomainIPLinks,
            ImageSearchIdentification,
            Cryptocurrencies,
            Messengers,
            Code,
            SearchEngines,
            ToolsForDuckDuckGo,
            ToolsForGoogle,
            IOT,
            Archives,
            ArchivesOfDocuments,
            Datasets,
            PasswordsEmailsPhoneNumbers,
            PeopleSearch,
            SockPuppets,
            NOOSINTTools,
            ToolsCollections,
            Files,
            IMEISerialNumbers,
            NFT,
            KeywordsTrendsNewsAnalytics,
            AppsAndPrograms,
            BrandsCompaniesItems,
            Movies,
            TVRadio,
            VirtualMachinesLinux,
            MyProjects,
            Exit,
        ]
    }

    // これは、MenuItemの各項目に対応する文字列を返すメソッドです。
    pub fn to_str(&self) -> &'static str {
        match self {
            MenuItem::MapsGeolocationTransport(_) => "Maps, Geolocation and Transport",
            MenuItem::SocialMedia(_) => "Social Media",
            MenuItem::Downloaders(_) => "Downloaders",
            MenuItem::SocialMediaPhotos => "Social media and photos maps",
            MenuItem::NatureAviation => "Nature Aviation",
            MenuItem::Maritime => "Maritime",
            MenuItem::Railway => "Railway",
            MenuItem::Routes => "Routes",
            MenuItem::PoliticsConflicts => "Politics, conflicts and crisis",
            MenuItem::UrbanInfrastructure => "Urban and industrial infrastructure",
            MenuItem::Transport => "Transport",
            MenuItem::Communications => "Communications, Internet, Technologies",
            MenuItem::Tools => "Tools",
            MenuItem::StreetView => "Street View",
            MenuItem::Other => "Other",
            MenuItem::DomainIPLinks => "Domain/IP/Links",
            MenuItem::ImageSearchIdentification => "Image Search and Identification",
            MenuItem::Cryptocurrencies => "Cryptocurrencies",
            MenuItem::Messengers => "Messengers",
            MenuItem::Code => "Code",
            MenuItem::SearchEngines => "Search engines",
            MenuItem::ToolsForDuckDuckGo => "Tools for DuckDuckGo",
            MenuItem::ToolsForGoogle => "Tools for Google",
            MenuItem::IOT => "IOT",
            MenuItem::Archives => "Archives",
            MenuItem::ArchivesOfDocuments => "Archives of documents",
            MenuItem::Datasets => "Datasets",
            MenuItem::PasswordsEmailsPhoneNumbers => "Passwords, emails, phone numbers",
            MenuItem::PeopleSearch => "People search",
            MenuItem::SockPuppets => "Sock Puppets",
            MenuItem::NOOSINTTools => "NOOSINT tools",
            MenuItem::ToolsCollections => "Tools collections",
            MenuItem::Files => "Files",
            MenuItem::IMEISerialNumbers => "IMEI and serial numbers",
            MenuItem::NFT => "NFT",
            MenuItem::KeywordsTrendsNewsAnalytics => "Keywords, trends, news analytics",
            MenuItem::AppsAndPrograms => "Apps and programs",
            MenuItem::BrandsCompaniesItems => "Brands, companies, items",
            MenuItem::Movies => "Movies",
            MenuItem::TVRadio => "TV/Radio",
            MenuItem::VirtualMachinesLinux => "VirtualMachines/Linux distributions",
            MenuItem::MyProjects => "My Projects",
            MenuItem::Exit => "[ EXIT - Mischief managed! ]",
        }
    }
}
